apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: coming-worm-python 
  janus-idp.io/tekton: coming-worm-python
  backstage.io/kubernetes-id: coming-worm-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: coming-worm-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  