apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: coming-worm-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: coming-worm-python 
  name: coming-worm-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: coming-worm-python 
